# Generated by Django 3.0.4 on 2020-06-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_Name', models.CharField(max_length=10)),
                ('u_PassWord', models.CharField(max_length=20)),
            ],
        ),
    ]
